### ISSUE TITLE
ga_unsampled_download - downloads a .csv with HTML code instead of report data

### ISSUE THREAD

**Issue by NikosKavvadas** [MarkEdmondson1234/googleAnalyticsR#241]
## What goes wrong
Function downloads the requested .csv but the file contains HTML code rather than the data in the unsampled report. This was noted a couple of days ago, function result was the expected before.

## Steps to reproduce the problem
here is the code:
```
lapply(unsampled_reports$title, ga_unsampled_download, 
             accountId = ga_id, 
             webPropertyId = propertyID, 
             profileId = viewID, 
             downloadFile = TRUE)
```

## Actual output

```
lapply(unsampled_reports$title, ga_unsampled_download, 
              accountId = ga_id, 
              webPropertyId = propertyID, 
              profileId = viewID, 
              downloadFile = TRUE)

2019-03-14 11:41:08> Skipping token checks as using cache
2019-03-14 11:41:08> Request: https://www.googleapis.com/analytics/v3/management/accounts/xxxxxxxx/webproperties/UA-xxxxxxxx-x/profiles/xxxxxxxx/unsampledReports/
2019-03-14 11:41:08> Making new cache
2019-03-14 11:41:25> Forgetting cache
2019-03-14 11:41:25> Fetching analytics#unsampledReports
2019-03-14 11:41:25> 
2019-03-14 11:41:25> Paging through API - token:https://www.googleapis.com/analytics/v3/management/accounts/xxxxxxxx/webproperties/UA-xxxxxxxx-x/profiles/xxxxxxxx/unsampledReports?start-index=1001&max-results=1000
2019-03-14 11:41:25> Skipping token checks as using cache
2019-03-14 11:41:25> Request: https://www.googleapis.com/analytics/v3/management/accounts/xxxxxxxx/webproperties/UA-xxxxxxxx-x/profiles/xxxxxxxx/unsampledReports?start-index=1001&max-results=1000
2019-03-14 11:41:25> Making new cache
2019-03-14 11:41:38> Forgetting cache
2019-03-14 11:41:38> Fetching analytics#unsampledReports
2019-03-14 11:41:38> Skipping token checks as using cache
2019-03-14 11:41:38> Request: https://www.googleapis.com/drive/v2/files/xxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxx/
2019-03-14 11:41:38> Making new cache
2019-03-14 11:41:38> Forgetting cache
Downloading: 76 kB     2019-03-14 11:41:41> attribution weekly sales PS 20190304 20190310.csv successfully downloaded!
2019-03-14 11:41:41> Skipping token checks as using cache
2019-03-14 11:41:41> Request: https://www.googleapis.com/analytics/v3/management/accounts/xxxxxxxx/webproperties/UA-xxxxxxxx-x/profiles/xxxxxxxx/unsampledReports/
2019-03-14 11:41:41> Making new cache
```
And here is how it looks in the downloaded .csv:
![actual content](https://user-images.githubusercontent.com/45235422/54354715-3f4ecb80-464f-11e9-85d7-8b5d7dd1a1c6.PNG)

## Session Info

Please run `sessionInfo()` so we can check what versions of packages you have installed
![package version](https://user-images.githubusercontent.com/45235422/54352288-3824bf00-4649-11e9-9ce5-7c199f010904.PNG)

**Comment by MarkEdmondson1234** [comment]
It looks like you have lost authentication to Google Drive?  Can you reauthenticate with that?  But @j450h1 may have more insights.

**Comment by NikosKavvadas** [comment]
Thanks for your response Mark, will check with a colleague about re-authenticating and let you know whether the issue is resolved.

**Comment by NikosKavvadas** [comment]
Connections were re-authenticated, issue persists though. Something interesting before re-authenticating was that due to multiple accounts that were signed-in, was not possible to download a file directly from Gdrive. By deleting cookies and signing-out of other accounts was able to download the file directly from Gdrive, still the function returned HTML code in a .csv. Have re-authenticated using the same account that created the unsampled reports.

Can you please confirm you can download .csv files as expected using "ga_unsampled_download"?

**Comment by j450h1** [comment]
I'm able to download an unsampled report with the same account I created the sample report with. I discovered now that if you authenticate with a service account, this function will not work because the original unsampled report was setup with my credentials. Are you sure you are logged in as the same user that created the unsampled report? 

``` r
library(googleAnalyticsR)

# Add Google Drive to scopes
options(googleAuthR.scopes.selected = c("https://www.googleapis.com/auth/analytics",
                                        "https://www.googleapis.com/auth/webmasters",
                                        "https://www.googleapis.com/auth/drive"
                                        ))

# sign in through browser with the same account you created the unsampled report
ga_auth()

# Check if unsampled report is complete
ga_unsampled_list(
  Sys.getenv("ACCOUNTID"),
  Sys.getenv("WEBPROPERTYID"),
  Sys.getenv("PROFILEID")
)

# Download csv file
ga_unsampled_download(
  reportTitle = "Jas Test",
  Sys.getenv("ACCOUNTID"),
  Sys.getenv("WEBPROPERTYID"),
  Sys.getenv("PROFILEID")
)
```

<sup>Created on 2019-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
RESULTS: 

```
2019-03-18 16:43:17> Fetching analytics#unsampledReports
  |========================================================================| 100%
2019-03-18 16:43:19> Jas Test.csv successfully downloaded!
[1] "Jas Test.csv"
```

**Comment by j450h1** [comment]
However, at the same time if I login with another user who doesn't have access I get this error message instead of download the HTML as per: 

```
Request failed [403]. Retrying in 1 seconds...
Request failed [403]. Retrying in 2.6 seconds...
2019-03-18 16:53:49> Request Status Code: 403
Scopes: https://www.googleapis.com/auth/analytics https://www.googleapis.com/auth/webmasters https://www.googleapis.com/auth/drive
App key: 289759286325-da3fr5kq4nl4nkhmhs2uft776kdsggbo.apps.googleusercontent.com
Method: new_token
Error: API returned: User does not have sufficient permissions for this account.
```
And if try with the service token authentication:
```
2019-03-18 16:56:54> Fetching analytics#unsampledReports
Error: Only Google Drive download links are currently supported. 
      Contact your Analytics 360 account manager if you would like to change 
      the download location of your unsampled reports.
```
Looks like that error message needs to be adjusted for this use case. But the point is it doesn't even let you download anything.

@NikosKavvadas I notice you are doing lapply, which may or may not have unattended effects. Maybe there is a certain wait time that needs to happen. Just an idea and to minimize the things to troubleshoot, can you try just downloading one report?

**Comment by j450h1** [comment]
Also I'm using the same version of the package on my Mac. Let me try on a different Windows machine. 

```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleAnalyticsR_0.6.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0        rstudioapi_0.9.0  magrittr_1.5      tidyselect_0.2.5  R6_2.4.0         
 [6] rlang_0.3.1       httr_1.4.0        dplyr_0.8.0.1     tools_3.5.2       packrat_0.5.0    
[11] googleAuthR_0.7.0 askpass_1.1       fortunes_1.5-4    openssl_1.2.2     assertthat_0.2.0 
[16] digest_0.6.18     tibble_2.0.1      crayon_1.3.4      purrr_0.3.1       tidyr_0.8.3      
[21] curl_3.3          memoise_1.1.0     glue_1.3.0        compiler_3.5.2    pillar_1.3.1     
[26] jsonlite_1.6      pkgconfig_2.0.2 
```

**Comment by j450h1** [comment]
I'm able to reproduce the same results on my windows machine and download the csv file.

**Comment by j450h1** [comment]
```unsampled_reports$title```  Is that filtered to be only reports that are ```status == 'COMPLETED' ``` ? Anyways, let me know if you are able to download a single complete report as per my earlier suggestion.

**Comment by j450h1** [comment]
**UPDATE:** @NikosKavvadas I should have actually opened the csv file! Your right I see the same HTML, in the csv. I think Google must have updated the screen, so the webscraping that I was doing in the function to get the download link, is no longer valid. I'll try to have a look to update the function to see if there is still a way to get this link programmatically.

**Comment by j450h1** [comment]
@MarkEdmondson1234 Looks like I did webscraping only for large files > 25 MB, and I believe the root cause of this problem lies here: 

```
    r <- GET(
      download_link,
      add_headers(Authorization = document[["request"]][["headers"]][["Authorization"]]),
      write_disk(filename, overwrite = TRUE),
      progress(),
      verbose = TRUE
    )
```
In particular, this Authorization process is no longer valid to add header as such. If you take the download link, copy and paste into a signed in browser window the csv file (actual csv) downloads fine.

**Comment by MarkEdmondson1234** [comment]
The web scraping is always going to be fragile as you will need to update the code each time Google changes the page, is there any options for generating the download URL directly or offloading work to another package?

**Comment by MarkEdmondson1234** [comment]
> Looks like the other way to authenticate is through query string parameters as such:
> https://developers.google.com/drive/api/v3/query-parameters
> Or perhaps there is a way to better use Oauth with the googleAuthR package?

Yes `googleAuthR` can handle that authorisation, it is the same as what it is doing behind the scenes.  It would be something like `gar_api_generator(download_link, "GET", customConfig = httr::write_disk(filename, overwrite=TRUE))`

**Comment by j450h1** [comment]
> The web scraping is always going to be fragile as you will need to update the code each time Google changes the page, are there any options for generating the download URL directly or offloading work to another package?

I completely agree. I will test out this new way with a file over 25 mbs and hopefully it let's me download directly without having to scrape an additional page for the confirmation code.

**Comment by j450h1** [comment]
> > Looks like the other way to authenticate is through query string parameters as such:
> > https://developers.google.com/drive/api/v3/query-parameters
> > Or perhaps there is a way to better use Oauth with the googleAuthR package?
> 
> Yes `googleAuthR` can handle that authorisation, it is the same as what it is doing behind the scenes. It would be something like
> 
> ```
> gar_api_generator(download_link, 
>                   "GET", 
>                   customConfig = list(httr::write_disk(filename, overwrite=TRUE))                         
>                  )
> ```
> If its a raw CSV file may also need to turn the [JSON parsing checks off too](https://code.markedmondson.me/googleAuthR/articles/advanced-building.html#skip-parsing), via `options(googleAuthR.rawResponse = TRUE)` so:
> 
> ```
> options(googleAuthR.rawResponse = TRUE)
> f <- gar_api_generator(download_link, 
>                  "GET", 
>                  customConfig = list(httr::write_disk(filename, overwrite=TRUE))                         
>                 )
> req <- f()
> options(googleAuthR.rawResponse = FALSE)
> 
> req
> ```

Actually, this did not end up working as the "csv" file returned shows up as: 

```
{"error":{"errors":[{"domain":"global","reason":"invalidAltValue","message":"Unknown output format: media/","locationType":"parameter","location":"alt"}],"code":400,"message":"Unknown output format: media/"}}
```

Looks like the root cause was not related to the way I authenticated, but rather the type of link I was using. In the past, I used the **webContentLink** which looks like: 

https://drive.google.com/a/cardinalpath.com/uc?id=1DcbQo-nrFcDahgvw9MQ1JTPUUZR0frxc&export=download

Now, I went ahead and tried the **selflink** and appended ?alt=media as described here: https://developers.google.com/drive/api/v3/manage-downloads
which looks like:

https://www.googleapis.com/drive/v2/files/1DcbQo-nrFcDahgvw9MQ1JTPUUZR0frxc?alt=media

Anyways, I was able to use the original code now that I use this download link and it works!

```
  r <- GET(
      download_link,
      add_headers(Authorization = document[["request"]][["headers"]][["Authorization"]]),
      write_disk(filename, overwrite = TRUE),
      progress()
    )
```
Anyways, let me do some further testing on a large file and then I will make a commit.

**Comment by j450h1** [comment]
I've updated as such to separate out the query parameter:
```
  r <- GET(
      download_link,
      query = list(alt = "media"),
      add_headers(Authorization = document[["request"]][["headers"]][["Authorization"]]),
      write_disk(filename, overwrite = TRUE),
      progress()
    )
r
```
I would still like to use gar_api_generator to keep things consistent with many other functions in the package and have less code, but now I'm getting a JSON result which has metadata about the file including the links. Any suggestions or should I just stick to what works above?

```
options(googleAuthR.rawResponse = TRUE)
f <- gar_api_generator(download_link, 
                 "GET", 
                 customConfig = list(httr::write_disk(filename, overwrite=TRUE),
                                     query = list(alt = "media")
                                     )                         
                )
req <- f()
options(googleAuthR.rawResponse = FALSE)

req
```

Response [https://www.googleapis.com/drive/v2/files/1DcbQo-nrFcDahgvw9MQ1JTPUUZR0frxc/]
  Date: 2019-03-20 08:05
  Status: 200
  Content-Type: application/json; charset=UTF-8
  Size: 3.16 kB
<ON DISK>  Jas Test.csv

**Comment by j450h1** [comment]
> > The web scraping is always going to be fragile as you will need to update the code each time Google changes the page, are there any options for generating the download URL directly or offloading work to another package?
> 
> I completely agree. I will test out this new way with a file over 25 mbs and hopefully it let's me download directly without having to scrape an additional page for the confirmation code.

I've manually uploaded a large file to Google Drive. Was able to download that by manually building the download link with the file id. Will look into seeing if I have an unsampled report to test tomorrow, in theory it should be the same result since there are no documented file size limitations using this method (other method said 10 mbs, but it seemed to be for files larger than 25 mb). See the PR.

**Comment by j450h1** [comment]
> I've updated as such to separate out the query parameter:
> 
> ```
>   r <- GET(
>       download_link,
>       query = list(alt = "media"),
>       add_headers(Authorization = document[["request"]][["headers"]][["Authorization"]]),
>       write_disk(filename, overwrite = TRUE),
>       progress()
>     )
> r
> ```
> I would still like to use gar_api_generator to keep things consistent with many other functions in the package and have less code, but now I'm getting a JSON result which has metadata about the file including the links. Any suggestions or should I just stick to what works above?
> 
> ```
> options(googleAuthR.rawResponse = TRUE)
> f <- gar_api_generator(download_link, 
>                  "GET", 
>                  customConfig = list(httr::write_disk(filename, overwrite=TRUE),
>                                      query = list(alt = "media")
>                                      )                         
>                 )
> req <- f()
> options(googleAuthR.rawResponse = FALSE)
> 
> req
> ```
> Response [https://www.googleapis.com/drive/v2/files/1DcbQo-nrFcDahgvw9MQ1JTPUUZR0frxc/]
> Date: 2019-03-20 08:05
> Status: 200
> Content-Type: application/json; charset=UTF-8
> Size: 3.16 kB
> Jas Test.csv

@MarkEdmondson1234 This should answer your question on the PR regarding gar_api_generator(). Feel free to take a crack at it.

**Comment by MarkEdmondson1234** [comment]
Keeping this open to look at possible update of authentication.

**Comment by MarkEdmondson1234** [comment]
But should now work if @NikosKavvadas wants to try it out with the latest version

**Comment by NikosKavvadas** [comment]
hello guys, many thanks for your responses. I have downloaded the latest version but am still getting the same result. maybe the issue is on my side after all

**Comment by MarkEdmondson1234** [comment]
Try making a new authentication token, then test again?

**Comment by NikosKavvadas** [comment]
Tried a new authentication token without much luck. Not sure what I am doing wrong so created an alternative approach in my script to download these .csv files

**Comment by j450h1** [comment]
Are you getting the exact same error message? That's too bad. Would like to try to reproduce but I understand the data is confidential. I'm open to doing a screen share to help troubleshoot if you want to give it another shot. I can show how I can successfully do it and maybe you can see what is different?. Feel free to send me an email to schedule a time.

**Comment by NikosKavvadas** [comment]
yes was getting the same error. nah no need to bother since you can successfully do this, most probably i am doing something wrong with the authentication. thanks for the suggestion :)

**Comment by j450h1** [comment]
@MarkEdmondson1234 I think the reason for this error is that the current package version on CRAN doesn't have the latest code I pushed for this ```ga_unsampled_download()``` function (I looked at the source code for version with ```View()```. I can confirm shortly when I install the github version with the latest commit.

**Comment by j450h1** [comment]
@MarkEdmondson1234 I can confirm this is indeed the case. I also just pushed a new commit to fix a bug with the ```downloadFile=FALSE``` option (i.e. retrieving data as a dataframe). Any estimated timeline on a new CRAN release?

**Comment by MarkEdmondson1234** [comment]
@j450h1 sorry I missed your question.  I'm updating googleAuthR to a new backend so will look at a new release after that is finalised, hopefully by end of summer

**Comment by j450h1** [comment]
@MarkEdmondson1234 No problem. Sounds good. Thanks for the update.
