### ISSUE TITLE
Error when anti-sample includes some 0-row data.frames, names are all NULL

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleAnalyticsR#42]
Treat this better:

```r
Error in fetch_google_analytics_4(requests, merge = TRUE) : 
  List of dataframes have non-identical column names. Got NULL NULL NULL NULL NULL NULL NULL NULL NULL NULL NULL NULL NULL 
9.
stop("List of dataframes have non-identical column names. Got ", 
    paste(lapply(out, function(x) names(x)), collapse = " ")) 
8.
fetch_google_analytics_4(requests, merge = TRUE) 
7.
google_analytics_4(viewId = viewId, date_range = c(x$start_date, 
    x$end_date), metrics = metrics, dimensions = dimensions, 
    dim_filters = dim_filters, met_filters = met_filters, filtersExpression = filtersExpression, 
    order = order, segments = segments, pivots = pivots, cohorts = cohorts,  ... 
6.
FUN(X[[i]], ...) 
5.
lapply(new_date_ranges, function(x) {
    if (x$range_date > 1) {
        myMessage("Anti-sample call covering ", x$range_date, 
            " days: ", x$start_date, ", ", x$end_date, level = 3) ... 
4.
anti_sample(viewId = viewId, date_range = date_range, metrics = metrics, 
    dimensions = dimensions, dim_filters = dim_filters, met_filters = met_filters, 
    filtersExpression = filtersExpression, order = order, segments = segments, 
    pivots = pivots, cohorts = cohorts, metricFormat = metricFormat,  ... 
3.
googleAnalyticsR::google_analytics_4(viewId = id, date_range = c(start, 
    end), metrics = metrics, dimensions = dimensions, filtersExpression = filters, 
    segments = segment, anti_sample = anti_sample, max = max_results) at misc.R#188
2.
iihGoogleAnalytics(id = ga_viewId, start = as.Date("2016-01-01"), 
    end = Sys.Date(), metrics = c("adClicks", "CTR", "CPC", "sessions", 
        "bounces", "adCost", "goalCompletionsAll", "goal9Completions", 
        "goal11Completions"), dimensions = c("date", "campaign",  ... at xxx_functions.R#213
1.
SEM_data(ga_viewId = ga_viewId) 

```

**Comment by MarkEdmondson1234** [comment]
This occurred when the anti-sample period you queried included some 0-row data.frames (e.g. a campaign stopped for a while) which caused the whole fetch to stop with error.  Should now be fixed.

**Comment by martijnvv** [comment]
I still get this error when I run a query:

`google_analytics_4(viewId, 
                                    date_range = c(dateStart, dateYesterday),
                                    dimensions=c("deviceCategory", "segment"), 
                                    metrics = c("uniqueEvents"),
                                    order = order_type("deviceCategory", "ASCENDING"),
                                    segments = seg_fun3,
                                    dim_filters = fc4,
                                    anti_sample = TRUE)`

I'm running version 0.3.0 of the package

**Comment by MarkEdmondson1234** [comment]
Hi @martijnvv I think this is fixed for the Github version, download from there and try again.  Version 0.3.0.9000 available via `devtools::install_github("MarkEdmondson1234/googleAnalyticsR")`.

Let me know.

**Comment by martijnvv** [comment]
Works like a charm. Thanks!
